# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: Ensure nginx {{ nginx_version }} is present
  package:
    name: "https://nginx.org/packages/rhel/7/x86_64/RPMS/nginx-{{ nginx_version }}-1.el7.ngx.x86_64.rpm"
    state: present
    update_cache: yes
  notify: Restart nginx
  tags: installation

- name: Start nginx on boot
  systemd:
    name: nginx
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: configuration

- name: Make NGiNX directory for custom configs
  become_method: sudo
  file: 
    path: /etc/nginx/conf.d
    state: directory
  tags: configuration

- name: Copy custom proxy.conf from local to remote
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  become_method: sudo
  tags: configuration

- name: Replace default nginx.conf
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become_method: sudo
  tags: configuration

- name: Change owner of folder /var/lib/nginx to {{ jiskefet_user }}
  file:
    path: /var/lib/nginx
    state: directory
    recurse: yes
    owner: "{{ jiskefet_user }}"
    group: "{{ jiskefet_user }}"
  become_method: sudo
  tags: configuration

- name: Remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Test NGiNX config
  command: nginx -T
  become_method: sudo
  tags: configuration

- name: Setup firewall to allow connections to port 80 and 443
  become_method: sudo
  command: "{{ item }}"
  with_items:
  - firewall-cmd --permanent --zone=public --add-service=http
  - firewall-cmd --permanent --zone=public --add-service=https
  notify: restart firewalld
  tags: configuration

- name: Allow http network to connect in SELinux
  become_method: sudo
  command: setsebool httpd_can_network_connect on -P
  tags: configuration

...