---
- name: Ensure nginx {{ nginx_version }} is present
  package:
    name: "https://nginx.org/packages/rhel/7/x86_64/RPMS/nginx-{{ nginx_version }}-1.el7.ngx.x86_64.rpm"
    state: present
    update_cache: yes
  notify: Restart nginx
  tags: installation

- name: Copy main page
  copy:
    src: "{{ role_path }}/files/index.html"
    dest: /var/www/html/
  tags: installation

- name: Deploy main configuration file
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Restart nginx
  tags: configuration

- name: Start nginx on boot
  systemd:
    name: nginx
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: configuration

- name: Open port {{ nginx_port }} in firewall
  firewalld:
    port: "{{ nginx_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes
  tags: configuration
