---
- name: login onto ubuntu vm and ping vm
  hosts: VM-Host
  remote_user: testuser
  tasks:
  - ping:
  - name: install "pm2" node.js package
    npm:
      name: pm2
      global: yes
    become: true
    become_method: su
    become_user: root
  - name: install "pm2 typescript interperter"
    command: pm2 install typescript
    become: true
    become_method: su
    become_user: root
# - name: install nginx
#   yum:
#     name: nginx
#     state: latest
#   become: true
#   become_method: su
#   become_user: root
  - name: make jiskefet home directory
    file: 
      path: /var/lib/jiskefet
      state: directory
    become: true
    become_method: su
    become_user: root
#  - name: go to project directory
#    command: cd /home/testuser/Project/s4s-webdev-api-assignment
#    register: out
#  - debug: var=out.stdout_lines
# TODO: git clone project
  - name: make nginx directory
    file: 
      path: /etc/nginx/sites-enabled
      state: directory
  - name: copy proxy.conf from local to remote
    copy:
      src: /home/calvinh/Desktop/proxy.conf
      dest: /etc/nginx/sites-enabled/proxy.conf
    become: true
    become_method: su
    become_user: root
  - name: test nginx config
    command: nginx -T
    become: true
    become_method: su
    become_user: root
  - name: start/reload the proxy.conf
    command: nginx -s reload
    become: true
    become_method: su
    become_user: root
  - name: list ports to see if proxy is running
    command: ss -ntl
    register: out
  - debug: var=out.stdout_lines
  - name: go to project directory and start project using pm2
    command: pm2 start -i max npm -- run start
    args:
      chdir: /home/testuser/Project/s4s-webdev-api-assignment