---
- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: "{{ remote_privileged_user }}"
  become: yes
  vars:
    - temp_folder: /tmp
  
  roles:
  - nginx
  - nodejs
  - web
  - ntp-client