# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: Check if .env exists in jiskefet-ui project
  stat:
    path: /var/lib/jiskefet/jiskefet-ui/.env
  register: stat_result


- name: Copy jiskefet-ui.env to jiskefet-ui project if it does not exist
  when: stat_result.stat.exists == False 
  copy:
    src: files/environments/jiskefet-ui.env
    dest: /var/lib/jiskefet/jiskefet-ui/.env

- name: Check if .env exists in jiskefet-api project
  stat:
    path: /var/lib/jiskefet/jiskefet-api/.env
  register: stat_result

- name: Copy jiskefet-api.env to remote if it does not exist
  when: stat_result.stat.exists == False 
  copy:
    src: files/environments/jiskefet-api.env
    dest: /var/lib/jiskefet/jiskefet-api/.env

- name: Set port number of the API server to {{ api_port_number }}
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    regexp: 'PORT=(.*)$'
    line: "PORT={{ api_port_number }}"
    backrefs: yes   

- name: Create ormconfig.json file if it does not exist
  copy:
    dest: /var/lib/jiskefet/jiskefet-api/ormconfig.json
    content: "{{ database_config }}"
...
