# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: Check if .env exists in jiskefet-ui project
  stat:
    path: /var/lib/jiskefet/jiskefet-ui/.env
  register: stat_result


- name: Copy jiskefet-ui.env to jiskefet-ui project if it does not exist
  when: stat_result.stat.exists == False 
  copy:
    src: files/environments/jiskefet-ui.env.template
    dest: /var/lib/jiskefet/jiskefet-ui/.env

- name: Set general settings for jiskefet-ui env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-ui/.env
    regexp: "{{ item.key }}=(.*)$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_ui_settings }}"

- name: Check if .env exists in jiskefet-api project
  stat:
    path: /var/lib/jiskefet/jiskefet-api/.env
  register: stat_result

- name: Copy jiskefet-api.env to remote if it does not exist
  when: stat_result.stat.exists == False 
  copy:
    src: files/environments/jiskefet-api.env.template
    dest: /var/lib/jiskefet/jiskefet-api/.env

- name: Set general settings for jiskefet-api env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    regexp: "{{ item.key }}=(.*)$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_api_general_settings }}"

- name: Set CERN settings for jiskefet-api env
  when: use_cern_sso == "true"
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    regexp: "{{ item.key }}=(.*)$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_api_cern_settings }}"

- name: Set Github settings for jiskefet-api env
  when: use_cern_sso == "false"
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    regexp: "{{ item.key }}=(.*)$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_api_github_settings }}"

- name: Set optional settings for jiskefet-api env
  when: use_cern_sso == "false"
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    regexp: "{{ item.key }}=(.*)$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_api_optional_settings }}"
...
