--- # Install mariadb via ansible on centOS
- name: Get variables
  include_vars: vars/variables.yml

- name: Install MYSQL
  become: true
  become_user: root
  yum:
    name: mariadb-server #debian: mysql-server
    state: present

- name: Install the Python MySQL Support Libraries
  become: true
  become_user: root
  yum: pkg=MySQL-python state=latest

- name: Start mysql server and enable it on reboot
  become: true
  become_user: root
  service: name=mariadb state=started enabled=true #debian: mysql

- name: Remove test db if it exists
  mysql_db: name=test state=absent

- name: Remove all anonymous users
  mysql_user: name='' host_all=yes state=absent

- name: Output ansible hostname
  debug: msg="Hostname is {{ ansible_hostname }}"

- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

# - name: Copy the root credentials as .my.cnf file
#   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

- name: Create a New Test DB called jiskefet
  mysql_db: name=jiskefet state=present login_user=root login_password={{ mysql_root_password }}
      
#
#
#templates/root.cnf.j2
#
#[client]
#user=root
#password={{ mysql_root_pass }}
...