# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

--- # Install mariadb via ansible on centOS
- name: Add official MariaDB repository
  become: yes
  become_user: root
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://yum.mariadb.org/10.1/centos7-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: mariadb

- name: Install packages
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: installed
  with_items: 
    - MariaDB
    - MariaDB-server
    - MySQL-python
  tags: mariadb
#

- name: Start mysql server and enable it on reboot
  become: true
  become_user: root
  service: name=mariadb state=started enabled=true #debian: mysql

# need to fix these

# - name: Remove test db if it exists
#   mysql_db: name=test state=absent

# - name: Remove all anonymous users
#   become: true
#   become_user: root
#   mysql_user: name='' host_all=yes state=absent

- name: Output ansible hostname
  debug: msg="Hostname is {{ ansible_hostname }}"

- name: Update mysql root password for all root accounts
  become: yes
  become_user: root
  mysql_user:
    name: "{{ database_config.username }}"
    host: "{{ item }}"
    password: "{{ database_config.password }}"
    login_user: "{{ database_config.username }}"
    login_password: "{{ database_config.password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
    - "%"

# - name: Copy the root credentials as .my.cnf file
#   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

- name: Create a New Test DB called {{ database_config.database }}
  mysql_db: name={{ database_config.database }} state=present login_user={{ database_config.username }} login_password={{ database_config.password }}

- name: Add firewall exceptions
  become: yes
  become_user: root
  command: firewall-cmd --permanent --add-service=mysql 

- name: Reload firewall
  become: yes
  become_user: root
  command: firewall-cmd --reload

#
#
#templates/root.cnf.j2
#
#[client]
#user=root
#password={{ mysql_root_pass }}
...