- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Ensure nginx is installed.
  yum:
    name: nginx
    state: present

- name: Start NGiNX
  service:
    name: nginx
    state: started