---
- name: Add epel-release repo
  become: yes
  become_user: root
  yum:
    name: epel-release
    state: present

- name: Ensure nginx is installed.
  become: yes
  become_user: root
  yum:
    name: nginx
    state: present

- name: Make nginx directory
  become: yes
  become_user: root
  file: 
    path: /etc/nginx/sites-enabled
    state: directory

- name: Copy proxy.conf from local to remote
  copy:
    src: proxy.conf
    dest: /etc/nginx/sites-enabled/proxy.conf
  become: true
  become_method: su
  become_user: root

# - name: Start/reload the proxy.conf
#   command: nginx -s reload
#   become: true
#   become_method: su
#   become_user: root

- name: Test nginx config
  command: nginx -T
  become: true
  become_method: su
  become_user: root

- name: Start NGiNX
  become: true
  become_user: root
  service:
    name: nginx
    state: started

- name: list ports to see if proxy is running
  command: ss -ntl
  register: out

- debug: var=out.stdout_lines
    
...