# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */
---
- name: install "pm2" node.js package
  npm:
    name: pm2
    global: yes
  become: true
  become_method: su
  become_user: root

- name: install "pm2 typescript interperter"
  command: pm2 install typescript
  become: true
  become_method: su
  become_user: root

- name: Copy ecosystem.config.js from local to remote
  copy:
    src: ecosystem.config.js
    dest: /var/lib/jiskefet/ecosystem.config.js
  become: true
  become_method: su
  become_user: root

- name: go to jiskefet-ui project directory and start project using pm2
  command: pm2 start ecosystem.config.js
  args:
    chdir: "/var/lib/jiskefet"

- name: list ports to see if proxy is running
  command: ss -ntl
  register: out

- debug: var=out.stdout_lines

- name: save current pm2 processes
  command: pm2 save

- name: set pm2 to run on system startup
  command: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u jiskefet-api --hp /var/lib/jiskefet
  become: true
  become_method: su
  become_user: root

...