---
- name: install "pm2" node.js package
  npm:
    name: pm2
    global: yes
  become: true
  become_method: su
  become_user: root

- name: install "pm2 typescript interperter"
  command: pm2 install typescript
  become: true
  become_method: su
  become_user: root

- name: list ports to see if proxy is running
  command: ss -ntl
  register: out

- debug: var=out.stdout_lines

# # either create a new or copy the a local ecosystem.config.js for pm2
# - name: go to project directory and generate an ecosystem.config.js
#   command: pm2 init
#   args:
#     chdir: "/var/lib/jiskefet/jiskefet-api"

- name: go to project directory and start project using pm2
  command: pm2 start -i max npm -- run start
  args:
    chdir: "/var/lib/jiskefet/jiskefet-api"

- name: save current pm2 processes
  command: pm2 save

- name: set pm2 to run on system startup
  command: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u jiskefet-api --hp /var/lib/jiskefet
  become: true
  become_method: su
  become_user: root

...