---
- name: install "pm2" node.js package
  npm:
    name: pm2
    global: yes
  become: true
  become_method: su
  become_user: root

- name: install "pm2 typescript interperter"
  command: pm2 install typescript
  become: true
  become_method: su
  become_user: root

- name: list ports to see if proxy is running
  command: ss -ntl
  register: out

- debug: var=out.stdout_lines

- name: go to project directory and start project using pm2
  npm: 
    path: "{{ path_to_api }}"

- name: go to project directory and start project using pm2
  command: pm2 start -i max npm -- run start
  args:
    chdir: "{{ path_to_api }}"

- name: set pm2 to run on system startup
  command: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u jiskefet-api --hp /home/jiskefet-api
  become: true
  become_method: su
  become_user: root
...