# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
# Set default variables
- import_tasks: set-default-values.yml

# Check variables
- import_tasks: check-variables.yml

- name: ping hosts
  command: ping -c 1 {{ item }}
  register: ping_results
  ignore_errors: yes
  with_items:
  - "{{ groups.all }}"

- name: filter ping_result and check which host has a return code of 0
  debug:
    var: item
  register: online_hosts
  with_items: "{{ ping_results | json_query(unreachable_ping) }}"
  vars:
    unreachable_ping: "results[?to_string(rc) == '0'].{ host: item}"

# Check ssh
- include_tasks: test-ssh.yml
  when: online_hosts.results | length > 0

# Do vault interaction
- include_tasks: interact-vault.yml
  with_items: "{{ unable_to_connect_to_hosts | json_query(get_hosts) }}"
  vars:
    get_hosts: "results[*].item.host"
  loop_control:
    loop_var: host
  when: unable_to_connect_to_hosts.results | length > 0
...
