# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: Setup firewall to allow connections to Jenkins on port specified as var.
  become: true
  become_user: root
  command: "{{ item }}"
  with_items:
  - firewall-cmd --zone=public --add-port={{ jenkins_http_port }}/tcp --permanent
  - firewall-cmd --reload
...