# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: restart NGiNX
  become: yes
  become_user: "{{ remote_privileged_user }}"
  service:
    name: nginx
    state: restarted
  tags:
    - git_pull

- name: restart firewalld
  become: yes
  become_user: "{{ remote_privileged_user }}"
  service:
    name: firewalld
    state: restarted
...
