# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: Check if .env exists in jiskefet-ui project
  stat:
    path: /var/lib/jiskefet/jiskefet-ui/.env
  register: stat_result
  become_user: "{{ jiskefet_user }}"

- name: Create .env in jiskefet-ui if it does not exist.
  when: stat_result.stat.exists == False 
  file:
    path: /var/lib/jiskefet/jiskefet-ui/.env
    state: touch
  become_user: "{{ jiskefet_user }}"

- name: Set general settings for jiskefet-ui .env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-ui/.env
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_ui_settings }}"
...