---
- name: Copy custom proxy.conf from local to remote
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  become_method: sudo
  tags: configuration

- name: Replace default nginx.conf
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become_method: sudo
  tags: configuration

- name: Change owner of folder /var/lib/nginx to {{ jiskefet_user }}
  file:
    path: /var/lib/nginx
    state: directory
    recurse: yes
    owner: "{{ jiskefet_user }}"
    group: "{{ jiskefet_user }}"
  become_method: sudo
  tags: configuration

- name: Remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Test NGiNX config
  command: nginx -T
  become_method: sudo
  tags: configuration
...