---
- name: Create db user for Jiskefet
  mysql_user:
    name: "{{ jiskefet_api_general_settings.TYPEORM_USERNAME }}"
    password: "{{ jiskefet_api_general_settings.TYPEORM_PASSWORD }}"
    priv: '*.*:ALL'
    state: present

- name: Create a new database with name {{ jiskefet_api_general_settings.TYPEORM_DATABASE }} 
  mysql_db:
    name: "{{ jiskefet_api_general_settings.TYPEORM_DATABASE }}"
    login_user: "{{ jiskefet_api_general_settings.TYPEORM_USERNAME }}"
    login_password: "{{ jiskefet_api_general_settings.TYPEORM_PASSWORD }}"
    state: present
...