---
- name: checkout jiskefet-api
  git:
    repo: "{{ remote_repository_url.JISKEFET_API }}"
    dest: /var/lib/jiskefet/jiskefet-api
    force: yes
    version: "{{ repository_branch.JISKEFET_API }}"
  become_user: "{{ jiskefet_user }}"
  tags:
    - git_pull
...