# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: Check if .env exists in jiskefet-ui project
  stat:
    path: /var/lib/jiskefet/jiskefet-ui/.env
  register: stat_result
  become_user: "{{ jiskefet_user }}"

- name: Create .env in jiskefet-ui if it does not exist.
  when: stat_result.stat.exists == False 
  file:
    path: /var/lib/jiskefet/jiskefet-ui/.env
    state: touch
  become_user: "{{ jiskefet_user }}"

- name: Set general settings for jiskefet-ui .env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-ui/.env
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_ui_settings }}"

- name: Check if .env exists in jiskefet-api project
  stat:
    path: /var/lib/jiskefet/jiskefet-api/.env
  register: stat_result
  become_user: "{{ jiskefet_user }}"

- name: Create .env in jiskefet-api if it does not exist.
  when: stat_result.stat.exists == False 
  file:
    path: /var/lib/jiskefet/jiskefet-api/.env
    state: touch
  become_user: "{{ jiskefet_user }}"

- name: Set USE_CERN_SSO flag for jiskefet-api .env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    line: "{{ item.key }}={{ item.value }}"
  with_items: 
    - { key: USE_CERN_SSO, value: "{{ USE_CERN_SSO | lower}}" }

- name: Set general settings for jiskefet-api .env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_api_general_settings }}"

- name: Set OAuth settings for jiskefet-api .env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    regexp: "{{ item.key }}=(.*)$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_oauth_settings }}"

- name: Set CERN oauth settings for jiskefet-api .env
  when: USE_CERN_SSO | lower == "true"
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_cern_oauth_settings }}"

- name: Set optional settings for jiskefet-api .env
  lineinfile:
    path: /var/lib/jiskefet/jiskefet-api/.env
    regexp: "{{ item.key }}=(.*)$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ jiskefet_api_optional_settings }}"
...
