# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Ensure semanage is installed for port management
  become_method: sudo
  yum:
    name: policycoreutils-python
    state: present

- name: Ensure NGiNX is installed.
  become_method: sudo
  yum:
    name: nginx
    state: present

- name: Make NGiNX directory for custom configs
  become_method: sudo
  file: 
    path: /etc/nginx/conf.d
    state: directory

- name: Copy custom proxy.conf from local to remote
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  become_method: sudo

- name: Replace default nginx.conf
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become_method: sudo

- name: Change owner of folder /var/lib/nginx to {{ jiskefet_user }}
  file:
    path: /var/lib/nginx
    state: directory
    recurse: yes
    owner: "{{ jiskefet_user }}"
    group: "{{ jiskefet_user }}"
  become_method: sudo

- name: Test NGiNX config
  command: nginx -T
  become_method: sudo

- name: Stop NGiNX services
  become_method: sudo
  service:
    name: nginx
    state: stopped

- name: Setup firewall to allow connections to port 80 and 443
  become_method: sudo
  command: "{{ item }}"
  with_items:
  - firewall-cmd --permanent --zone=public --add-service=http
  - firewall-cmd --permanent --zone=public --add-service=https
  notify: restart firewalld

- name: Allow http network to connect in SELinux
  become_method: sudo
  command: setsebool httpd_can_network_connect on -P

- name: Set NGiNX to start on startup
  become_method: sudo
  command: systemctl enable nginx
  notify: restart NGiNX
...