# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: install "pm2" node.js package
  npm:
    name: pm2
    global: yes
  become: true
  become_method: su
  become_user: root

- name: install "pm2 typescript interperter"
  command: pm2 install typescript
  become: true
  become_method: su
  become_user: root

- name: Copy ecosystem.json from local to remote
  copy:
    src: ecosystem.json
    dest: /var/lib/jiskefet/ecosystem.json
  become: true
  become_method: su
  become_user: root

- name: stop current pm2 daemon if it exits
  command: pm2 kill

- name: go to jiskefet-ui project directory and start project using pm2
  command: pm2 start ecosystem.json
  args:
    chdir: "/var/lib/jiskefet"

- name: list all ports running on current host
  command: ss -ntl
  register: out

- debug: var=out.stdout_lines

- debug: var=out.stdout

- name: check if API is running on port {{ jiskefet_api_general_settings.PORT }}
  fail:
    msg: "API is unable to start, please use `pm2 logs` to view the error(s)"
  when: 'jiskefet_api_general_settings.PORT|string not in out.stdout'

- name: save current pm2 processes
  command: pm2 save

- name: set pm2 to run on system startup
  command: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u jiskefet-api --hp /var/lib/jiskefet
  become: true
  become_method: su
  become_user: root

...