# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: install "pm2" node.js package
  npm:
    name: pm2
    global: yes
  become_method: sudo

- name: install "pm2 typescript interperter"
  command: pm2 install typescript
  become_method: sudo

- name: Copy ecosystem.json from local to remote
  copy:
    src: ecosystem.json
    dest: /var/lib/jiskefet/ecosystem.json
  become_user: "{{ jiskefet_user }}"
  tags:
    - git_pull

- name: stop current pm2 daemon if it exits
  become_user: "{{ jiskefet_user }}"
  command: pm2 kill
  tags:
    - git_pull

- name: go to jiskefet project directory and start project using pm2
  command: pm2 start ecosystem.json --env {{ deploy_environment }}
  args:
    chdir: "/var/lib/jiskefet"
  become_user: "{{ jiskefet_user }}"
  tags:
    - git_pull

- name: check if API is running on port {{ jiskefet_api_general_settings.PORT }}
  wait_for:
    port: "{{ jiskefet_api_general_settings.PORT }}"
    delay: 10
    timeout: 50
  register: wait_for_output
  ignore_errors: yes

- name: print error when API is not running on port {{ jiskefet_api_general_settings.PORT }}
  vars:
    msg: |
        API is unable to start, please ssh to host:{{ play_hosts }} and run command `$ pm2 logs PM2 --lines 30` to view the error(s).
        If the error(s) are not visible in the PM2 logs, please go to the directory of the API and run the command `$ npm run start` to view the error(s).
        Please run the ansible-playbook again after resolving the errors in order to let PM2 create the startup process.
  debug:
    msg: "{{ msg.split('\n') }}"
  failed_when: wait_for_output.failed == true

- name: save current pm2 processes
  command: pm2 save
  become_user: "{{ jiskefet_user }}"
  tags:
    - git_pull

- name: set pm2 to run on system startup
  command: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u "{{ jiskefet_user }}" --hp /var/lib/jiskefet
  become_method: sudo
  tags:
    - git_pull
...