# /*
#  * Copyright (C) 2018 Amsterdam University of Applied Sciences (AUAS)
#  *
#  * This software is distributed under the terms of the
#  * GNU General Public Licence version 3 (GPL) version 3,
#  * copied verbatim in the file "LICENSE"
#  */

---
- name: populate service facts
  service_facts:

- name: enable and start firewalld
  become: yes
  become_method: sudo
  become_user: "{{ remote_privileged_user }}"
  command: "systemctl {{ item }}"
  with_items:
  - enable firewalld
  - start firewalld
  when: ((ansible_facts.services['firewalld.service'] is undefined)
        or
        ((ansible_facts.services['firewalld.service'] is defined)
        and
        (ansible_facts.services['firewalld.service']['state'] != 'running')))


...
